In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\eszeu\anaconda3\lib\site-packages (1.4.2)
Requirement already satisfied: numpy>=1.18.5 in c:\users\eszeu\anaconda3\lib\site-packages (from pandas) (1.21.5)
Requirement already satisfied: pytz>=2020.1 in c:\users\eszeu\anaconda3\lib\site-packages (from pandas) (2021.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\eszeu\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\eszeu\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [3]:
import pandas as pd

In [4]:
pd

In [6]:
cases = pd.read_csv('COVID.csv')
cases

    country_ch        country_en       cases   deaths
0           美國     United States  34,516,883  622,158
1           印度             India  31,371,901  420,551
2           巴西            Brazil  19,688,663  549,924
3          俄羅斯            Russia   6,126,541  153,874
4           法國            France   5,993,937  111,644
..         ...               ...         ...      ...
190        萬那杜           Vanuatu           4        1
191      馬紹爾群島  Marshall Islands           4        0
192         帛琉             Palau           2        0
193        薩摩亞             Samoa           1        0
194   密克羅尼西亞聯邦        Micronesia           1        0

[195 rows x 4 columns]

In [7]:
cases_json = pd.read_json('COVID.json')
cases_json

    country_ch        country_en       cases   deaths
0           美國     United States  34,516,883  622,158
1           印度             India  31,371,901  420,551
2           巴西            Brazil  19,688,663  549,924
3          俄羅斯            Russia   6,126,541  153,874
4           法國            France   5,993,937  111,644
..         ...               ...         ...      ...
190        萬那杜           Vanuatu           4        1
191      馬紹爾群島  Marshall Islands           4        0
192         帛琉             Palau           2        0
193        薩摩亞             Samoa           1        0
194   密克羅尼西亞聯邦        Micronesia           1        0

[195 rows x 4 columns]

In [9]:
url = 'https://www.tiobe.com/tiobe-index/'
tables = pd.read_html(url, keep_default_na=False)
tables[0].head(20)

,Oct 2022,Oct 2021,Change,Programming Language,Programming Language.1,Ratings,Change.1
0,1,1,,,Python,17.08%,+5.81%
1,2,2,,,C,15.21%,+4.05%
2,3,3,,,Java,12.84%,+2.38%
3,4,4,,,C++,9.92%,+2.42%
4,5,5,,,C#,4.42%,-0.84%
5,6,6,,,Visual Basic,3.95%,-1.29%
6,7,7,,,JavaScript,2.74%,+0.55%
7,8,10,,,Assembly language,2.39%,+0.33%
8,9,9,,,PHP,2.04%,-0.06%
9,10,8,,,SQL,1.78%,-0.39%
10,11,12,,,Go,1.27%,-0.01%
11,12,14,,,R,1.22%,+0.03%
12,13,29,,,Objective-C,1.21%,+0.76%
13,14,13,,,MATLAB,1.18%,-0.02%
14,15,17,,,Swift,1.05%,-0.06%
15,16,16,,,Ruby,0.88%,-0.24%
16,17,11,,,Classic Visual Basic,0.87%,-0.96%
17,18,20,,,Delphi/Object Pascal,0.85%,-0.09%
18,19,18,,,Fortran,0.79%,-0.29%
19,20,26,,,Rust,0.70%,+0.17%

In [11]:
student_url = 'https://info.tku.edu.tw/basicdata1.aspx'
student_tables = pd.read_html(student_url, keep_default_na=False)
student_tables[0].head(5)

                                 é ç®/å­¸å¹´åº¦    108    109    110
0                                å¤§å­¸æ¥éé¨  20273  20239  20763
1  å¤§å­¸é²ä¿®å­¸å£«ç­åäºå¹´å¶å¨è·å°ç­   1429   1249   1146
2     ç¢©å£«ç­ãç¢©å£«å¨è·å°ç­ååå£«ç­   2933   2721   2625
3                    å­¸çäººæ¸åè¨ï¼äººï¼  24635  24209  24534

In [13]:
pip install requests

Requirement already satisfied: requests in c:\users\eszeu\anaconda3\lib\site-packages (2.27.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\eszeu\anaconda3\lib\site-packages (from requests) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\eszeu\anaconda3\lib\site-packages (from requests) (1.26.9)
Requirement already satisfied: idna<4,>=2.5 in c:\users\eszeu\anaconda3\lib\site-packages (from requests) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\eszeu\anaconda3\lib\site-packages (from requests) (2.0.4)
Note: you may need to restart the kernel to use updated packages.

In [14]:
import requests

result =  requests.get("https://info.tku.edu.tw/basicdata1.aspx")

In [15]:
result

NameError: name 'result' is not defined

In [16]:
result =  requests.get('https://info.tku.edu.tw/basicdata1.aspx')

In [18]:
print(result.text)

<!doctype html>
<html>
<head>
<title>淡江大學校務及財務資訊公開專區-學生人數與變動趨勢圖</title>
<meta charset="utf-8">
<!-- Meta -->
<meta name="keywords" content="" />
<meta name="author" content="">
<meta name="robots" content="" />
<meta name="description" content="" />

<!-- this styles only adds some repairs on idevices  -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

<!-- Favicon -->
<link rel="shortcut icon" href="images/favicon.ico">

<!-- Google fonts - witch you want to use - (rest you can just remove) -->
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Roboto:100,200,300,400,500,600,700,800,900' rel='stylesheet' type='text/css'>

<!--[if lt IE 9]>
<script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!-- stylesheets -->

<link rel="stylesheet" media="screen" href="js/bootstrap/bootstrap.min.css" type="text/css" />
<link rel="stylesheet" href="js/mainmenu/menu.css" type="text/css" />
<link rel="stylesheet" href="css/defaultx.css" type="text/css" />
<link rel="stylesheet" href="css/layouts.css" type="text/css" />
<link rel="stylesheet" href="css/shortcodes.css" type="text/css" />
<link rel="stylesheet" href="css/font-awesome/css/font-awesome.min.css">
<link rel="stylesheet" media="screen" href="css/responsive-leyoutsx.css" type="text/css" />
<link rel="stylesheet" type="text/css" href="css/Simple-Line-Icons-Webfont/simple-line-icons.css" media="screen" />
<link rel="stylesheet" href="css/et-line-font/et-line-font.css">
<link rel="stylesheet" href="css/optmz.css" />
<link rel="stylesheet" href="css/basicdata.css" />

<!-- Remove the below comments to use your color option -->
<!--<link rel="stylesheet" href="css/colors/lightblue.css" />-->
<!--<link rel="stylesheet" href="css/colors/orange.css" />-->
<!--<link rel="stylesheet" href="css/colors/green.css" />-->
<!--<link rel="stylesheet" href="css/colors/pink.css" />-->
<!--<link rel="stylesheet" href="css/colors/red.css" />-->
<!--<link rel="stylesheet" href="css/colors/purple.css" />-->
<!--<link rel="stylesheet" href="css/colors/bridge.css" />-->
<!--<link rel="stylesheet" href="css/colors/yellow.css" />-->
<!--<link rel="stylesheet" href="css/colors/violet.css" />-->
<!--<link rel="stylesheet" href="css/colors/cyan.css" />-->
<!--<link rel="stylesheet" href="css/colors/mossgreen.css" />-->
<style type="text/css">
@media only screen and (max-width:999px) and (min-width:480px){
	.table-style-2 td:nth-of-type(1):before { content: ""; }
	.table-style-2 td:nth-of-type(2):before { content: "(108學年度) "; }
	.table-style-2 td:nth-of-type(3):before { content: "(109學年度) "; }
	.table-style-2 td:nth-of-type(4):before { content: "(110學年度) "; }

}
@media only screen and (max-width: 479px){
	.table-style-2 td:nth-of-type(1):before { content: ""; }
	.table-style-2 td:nth-of-type(2):before { content: "(108學年度) "; }
	.table-style-2 td:nth-of-type(3):before { content: "(109學年度) "; }
	.table-style-2 td:nth-of-type(4):before { content: "(110學年度) "; }

}

</style>
</head>

<body>
<div class="site_wrapper">
    <div class="topbar orange2 topbar-padding">

  </div>
  <div class="clearfix"></div>

  <div id="header">
    <div class="container">
      <div class="navbar navbar-default yamm dark2">
        <div class="navbar-header">
          <button type="button" data-toggle="collapse" data-target="#navbar-collapse-grid" class="navbar-toggle two three"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>

        </div>
        <div id="navbar-collapse-grid" class="navbar-collapse collapse pull-right">
          <ul class="nav navbar-nav">


            <li class="dropdown"> <a href="option1.aspx" class="dropdown-toggle">校務資訊說明</a>
              <ul class="dropdown-menu" role="menu">
                	<li><a href="intro.aspx">學校沿革</a> </li>
                    <li><a href="https://about.tku.edu.tw/organize.html" target='_blank'> 組織架構</a> </li>

                    <li class="dropdown-submenu mul"> <a tabindex="-1" href="#">基本數據及趨勢 + </a>
                      <ul class="dropdown-menu">
                        <li><a href="basicdata1.aspx">學生人數與變動趨勢圖</a></li>
                        <li><a href="basicdata2.aspx">教職員人數與變動趨勢圖</a></li>
                        <li><a href="basicdata3.aspx">生師比與變動趨勢圖</a></li>
                        <li><a href="basicdata4.aspx">每生校地及校舍面積</a></li>
                        <li><a href="basicdata5.aspx">學校圖書資源</a></li>
                        <li><a href="basicdata6.aspx">學校設備與資源</a></li>
                      </ul>
                    </li>

                    <li><a href="prospect.aspx"> 學校特色與發展願景</a> </li>
                    <li class="dropdown-submenu mul"><a tabindex="-1" href="#"> 學校績效表現 + </a>
                      <ul class="dropdown-menu">
                        <li><a href="effects1.aspx">各類評鑑結果</a></li>
                        <li><a href="effects2.aspx">各項績效表現</a></li>
                        <li><a href="effects3.aspx">畢業生流向與校友表現</a></li>
                       </ul>
                    </li>
                    <li><a href="https://about.tku.edu.tw/trustees/index.asp" target="_blank" title="連結董事會專區(另開視窗)">私立學校董事會相關資訊</a> </li>

              </ul>
            </li>

            <li class="dropdown"> <a href="option2.aspx" class="dropdown-toggle">財務資訊分析</a>
              <ul class="dropdown-menu" role="menu">
                	<li><a href="in_out_analy.aspx">學校收入分析</a> </li>
                    <li><a href="in_out_analy2.aspx">學校支出分析</a> </li>
              </ul>
            </li>

            <li class="dropdown"> <a href="option3.aspx" class="dropdown-toggle">學雜費與就學補助資訊</a>
              <ul class="dropdown-menu" role="menu">
                	<li><a href="allowance.aspx">學雜費收費標準</a> </li>
                    <li><a href="allowance2.aspx">平均教學成本</a> </li>
                    <li><a href="allowance3.aspx">學雜費佔教學成本比率</a> </li>
                    <li><a href="allowance4.aspx">在學期間教育支出估算</a> </li>
                    <li><a href="allowance5.aspx">各項助學措施資訊</a> </li>
                    <li><a href="allowance6.aspx">就學貸款/獎助學金/學雜費減免</a> </li>
                    <li><a href="use_layout.aspx">學雜費調整之用途規劃說明</a> </li>
                    <li><a href="discussion.aspx">學雜費調整校內審議程序說明</a> </li>
              </ul>
            </li>

            <li class="dropdown"> <a href="option4.aspx" class="dropdown-toggle">學校其他重要資訊</a>
              <ul class="dropdown-menu three" role="menu">
                <li> <a href="budget.aspx">預算編審程序</a> </li>
                <li> <a href="report.aspx">會計師查核報告</a> </li>
                <li> <a href="purchase.aspx">學校採購情形</a> </li>
                <li> <a href="handle.aspx">處分土地及重大資產</a> </li>
                <li> <a href="course.aspx">課程與師資</a> </li>
                <li> <a href="others.aspx">其他</a> </li>
              </ul>
            </li>
            <li class="dropdown"> <a href="option5.aspx" class="dropdown-toggle">內控內稽執行情形</a>
              <ul class="dropdown-menu two" role="menu">
                <li> <a href="doc/control.pdf" target="_blank">內部控制制度手冊 </a></li>
                <li> <a href="audit.aspx">內部控制制度作業程序</a> </li>
                <li> <a href="audit_point.aspx">內部控制重點</a> </li>
                <li> <a href="audit_rule.aspx">內部稽核作業規範</a> </li>
                <li> <a href="audit_report.aspx">稽核計畫及稽核報告</a> </li>
              </ul>
            </li>
            <li class="dropdown"> <a href="https://about.tku.edu.tw/trustees/index.asp" target="_blank" title="連結董事會專區(另開新視窗)">董事會相關資訊</a></li>

          </ul>
        </div>
      </div>
    </div>
  </div>
  <!--end menu-->


  <section>
    <div class="header-inner two">
      <div class="inner text-center">
        <h4 class="title text-white uppercase">校務資訊說明</h4>
<!--        <h5 class="text-white uppercase">Get Many More Features</h5>-->
      </div>
      <div class="overlay bg-opacity-5"></div>
<!--      <img src="images/header-img1.jpg" alt="" class="img-responsive"/> -->
      </div>
  </section>
  <!-- end header inner -->
  <div class="clearfix"></div>

  <section>
    <div class="pagenation-holder">
      <div class="container">

        <div class="row">
          <div class="col-md-6">
            <h3>學生人數與變動趨勢圖</h3>
          </div>
          <div class="col-md-6 text-right">
            <div class="pagenation_links"><a href="index.aspx" title="回首頁"><i class="fa fa-home"></i></a><i> / </i> <a href="option1.aspx" title="回校務資訊說明選單">校務資訊說明</a> <i> / </i> <a href="basicdata.aspx" title="回基本數據及趨勢次選單">基本數據及趨勢</a> <i> / </i> 學生人數</div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--end section-->
  <div class="clearfix"></div>

 <section class="sec-padding">
    <div class="container">
      <div class="row">

        <div class="table-holder">
          <h3 class="section-title"><span class="text-orange-5">近3年學生人數</span></h3>
<!--        <div class="domain-pricing-table-holder">-->

          <table class="table-style-2 table-bordered">
            <thead>
              <tr>
                <th>項目/學年度</th>
                <th>108</th>
                <th>109</th>
                <th>110</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><div class="padding-left-1">大學日間部</div></td>
                <td><div class="text-right">20,273</div></td>
                <td><div class="text-right">20,239</div></td>
                <td><div class="text-right">20,763</div></td>
              </tr>
              <tr>
                <td><div class="padding-left-1">大學進修學士班及二年制在職專班</div></td>
                <td><div class="text-right">1,429</div></td>
                <td><div class="text-right">1,249</div></td>
                <td><div class="text-right">1,146</div></td>
              </tr>
              <tr>
                <td><div class="padding-left-1">碩士班、碩士在職專班及博士班</div></td>
                <td><div class="text-right">2,933</div></td>
                <td><div class="text-right">2,721</div></td>
                <td><div class="text-right">2,625</div></td>
              </tr>
              <tr class="subtotl">
                <td>學生人數合計（人） </td>
                <td><div class="text-right">24,635</div></td>
                <td><div class="text-right">24,209</div></td>
                <td><div class="text-right">24,534</div></td>
              </tr>
            </tbody>
          </table>
          <p class="text-red text-right">資料日期：每學年10月15日報部資料</p>
        </div>
      </div>
    </div>
  </section>
  <div class="clearfix"></div>
  <!-- end section -->


  <section class="sec-moreless-padding ">
  <div id="orgchart-section">
    <div class="container">

      <div class="row">

        <div class="content margin-top3">
          <h3 class="section-title"><span class="text-orange-5">近3年學生人數變動趨勢圖</span></h3>

            <img src="images/1-3-1.png" class="img-responsive col-centered" alt="近3年學生人數變動趨勢圖" title="近3年學生人數變動趨勢圖" />

        </div>
      </div>



    </div>
  </div>
  </section>
  <div class="clearfix"></div>
  <!-- end section -->

    <section class="footer section-fulldark sec-moreless-padding">
    <div class="container">
      <div class="row myfoot">
        <div class="col-md-4 col-sm-6 colmargin clearfix">
          <h6 class="uppercase footer-title less-mar3">資料維護</h6>
          <div class="footer-title-bottomstrip"></div>
          <div class="clearfix"></div>
          <ul class="address-info no-border">
            <li><i class="fa fa-pencil"></i> <a href="http://www.ac.tku.edu.tw/" target="_blank" title="連結秘書處網頁(另開視窗)">秘書處</a> 江雅玲、<a href="http://www.finance.tku.edu.tw/" target="_blank" title="連結財務處網頁(另開視窗)">財務處</a> 巫佩樺</li>

          </ul>
        </div>
        <!--end item-->

        <div class="col-md-3 col-sm-6 colmargin clearfix">
          <h6 class="uppercase footer-title less-mar3">網站建置</h6>
          <div class="footer-title-bottomstrip"></div>
          <div class="clearfix"></div>
          <ul class="address-info no-border">
            <li><i class="fa fa-gear"></i> <a href="http://www.ipc.tku.edu.tw" target="_blank" title="連結資訊處網頁(另開視窗)">資訊處</a> 張秀榕</li>
          </ul>
        </div>
        <!--end item-->

        <div class="col-md-3 col-sm-6 colmargin tex-left clearfix">
          <h6 class="uppercase footer-title less-mar3">更新日期</h6>
          <div class="footer-title-bottomstrip"></div>
          <div class="clearfix"></div>
          <ul class="usefull-links tex-left no-border">
            <li><i class="fa fa-calendar"></i>  2022-10-27</li>
          </ul>
        </div>
        <!--end item-->

        <div class="col-md-2 col-sm-6 colmargin tex-left clearfix">

          <span class="pull-right"><a href="https://www.tku.edu.tw" target="_blank" title="回淡江大學首頁"><img src="images/TKU-logo.png" class="img-responsive" /></a></span>

        </div>
        <!--end item-->

      </div>
    </div>
  </section>
  <!--end section-->
  <div class="clearfix"></div>

  <section class="section-copyrights sec-minless-padding">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="clearfix"></div>

          <p><span>淡江大學 版權所有 Copyright©2018 Tamkang University All rights reserved.</span></p>
		 </div>
      </div>
    </div>
  </section>
  <a href="#" class="scrollup"></a><!-- end scroll to top of the page-->


</div>
<!--end sitewraper-->

<!-- ========== Js files ========== -->

<script type="text/javascript" src="js/universal/jquery.js"></script>
<script src="js/bootstrap/bootstrap.min.js" type="text/javascript"></script>
<script src="js/mainmenu/customeUI.js"></script>
<script src="js/mainmenu/jquery.sticky.js"></script>
<script src="js/scrolltotop/totop.js"></script>

<script src="js/scripts/functions.js" type="text/javascript"></script>

</body>
</html>

In [34]:
student_table1 = pd.read_html(student_url,encoding ='utf-8')[0]
student_table1

            項目/學年度    108    109    110
0            大學日間部  20273  20239  20763
1  大學進修學士班及二年制在職專班   1429   1249   1146
2   碩士班、碩士在職專班及博士班   2933   2721   2625
3        學生人數合計（人）  24635  24209  24534

In [37]:
student_url2 = 'https://info.tku.edu.tw/in_out_analy2.aspx'

In [38]:
student_table2 = pd.read_html(student_url2,encoding ='utf-8')[0]
student_table2

   成本與費用項目/學年度         107                 108                 109
   成本與費用項目/學年度           元       %           元       %           元       %
0        董事會支出     4712199    0.14     5034515    0.14     4806637    0.14
1          人事費     3425297    0.10     3761400    0.11     3761400    0.11
2          業務費      294834    0.01      331545    0.01      221943    0.01
3          維護費       16380    0.00           0    0.00           0    0.00
4       出席及交通費      145000    0.00      105000    0.00      115000    0.00
5        折舊及攤銷      830688    0.02      836570    0.02      708294    0.02
6       行政管理支出   488447613   14.07   504067874   14.35   456937923   13.70
7          人事費   204075154    5.88   202868369    5.77   198804495    5.96
8          業務費   127588638    3.67   120314818    3.42   120503981    3.61
9          維護費    84750314    2.44    96504987    2.75    62266230    1.87
10       退休撫卹費    12142008    0.35    11079756    0.32     9296620    0.28
11       折舊及攤銷    59891499    1.72    73299944    2.09    66066597    1.98
12   教學研究及訓輔支出  2313419711   66.63  2196600215   62.52  2169719608   65.04
13         人事費  1580098453   45.51  1546308145   44.01  1562653376   46.84
14         業務費   407467633   11.74   345990767    9.85   329401798    9.87
15         維護費    22909258    0.66    18558123    0.53    11308646    0.34
16       退休撫卹費    66433179    1.91    74749632    2.13    62732749    1.88
17       折舊及攤銷   236511188    6.81   210993548    6.01   203623039    6.10
18      獎助學金支出   223669110    6.44   203602135    5.79   204513377    6.13
19       獎學金支出   104969227    3.02   102745121    2.92    97061795    2.91
20       助學金支出   118699883    3.42   100857014    2.87   107451582    3.22
21      推廣教育支出    90343484    2.60    88179181    2.51    78276580    2.35
22         人事費    58659384    1.69    60539377    1.72    58654839    1.76
23         業務費    28910275    0.83    25440175    0.72    17628174    0.53
24         維護費     1312583    0.04      743877    0.02      547312    0.02
25       退休撫卹費      415149    0.01      388118    0.01      281930    0.01
26       折舊及攤銷     1046093    0.03     1067634    0.03     1164325    0.03
27      產學合作支出   304968595    8.78   453321731   12.90   378423434   11.34
28         人事費   159890837    4.60   249362552    7.10   186177267    5.58
29         業務費   133546282    3.85   193542043    5.51   183775761    5.51
30       退休撫卹費      469175    0.01      635237    0.02      487971    0.01
31       折舊及攤銷    11062301    0.32     9781899    0.28     7982435    0.24
32        其他支出    46622454    1.34    62769313    1.79    43545359    1.31
33       試務費支出    14437884    0.42    12972638    0.37    10114202    0.30
34      財產交易短絀    21137167    0.61    37139473    1.06    19188567    0.58
35      超額年金給付    11047403    0.32    12657202    0.36    14242590    0.43
36         合　計  3472183166  100.00  3513574964  100.00  3336222918  100.00

In [40]:
result2 =  requests.get("https://info.tku.edu.tw/in_out_analy2.aspx")

In [42]:
print(result2.text)

<!doctype html>
<html>
<head>
<title>淡江大學校務及財務資訊公開專區-學校支出分析</title>
<meta charset="utf-8">
<!-- Meta -->
<meta name="keywords" content="" />
<meta name="author" content="">
<meta name="robots" content="" />
<meta name="description" content="" />

<!-- this styles only adds some repairs on idevices  -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

<!-- Favicon -->
<link rel="shortcut icon" href="images/favicon.ico">

<!-- Google fonts - witch you want to use - (rest you can just remove) -->
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Roboto:100,200,300,400,500,600,700,800,900' rel='stylesheet' type='text/css'>

<!--[if lt IE 9]>
<script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!-- stylesheets -->

<link rel="stylesheet" media="screen" href="js/bootstrap/bootstrap.min.css" type="text/css" />
<link rel="stylesheet" href="js/mainmenu/menu.css" type="text/css" />
<link rel="stylesheet" href="css/defaultx.css" type="text/css" />
<link rel="stylesheet" href="css/layouts.css" type="text/css" />
<link rel="stylesheet" href="css/shortcodes.css" type="text/css" />
<link rel="stylesheet" href="css/font-awesome/css/font-awesome.min.css">
<link rel="stylesheet" media="screen" href="css/responsive-leyoutsx.css" type="text/css" />
<link rel="stylesheet" type="text/css" href="css/Simple-Line-Icons-Webfont/simple-line-icons.css" media="screen" />
<link rel="stylesheet" href="css/et-line-font/et-line-font.css">
<link rel="stylesheet" href="css/optmz.css" />
<link rel="stylesheet" href="css/basicdata.css" />

<!-- Remove the below comments to use your color option -->
<!--<link rel="stylesheet" href="css/colors/lightblue.css" />-->
<!--<link rel="stylesheet" href="css/colors/orange.css" />-->
<!--<link rel="stylesheet" href="css/colors/green.css" />-->
<!--<link rel="stylesheet" href="css/colors/pink.css" />-->
<!--<link rel="stylesheet" href="css/colors/red.css" />-->
<!--<link rel="stylesheet" href="css/colors/purple.css" />-->
<!--<link rel="stylesheet" href="css/colors/bridge.css" />-->
<!--<link rel="stylesheet" href="css/colors/yellow.css" />-->
<!--<link rel="stylesheet" href="css/colors/violet.css" />-->
<!--<link rel="stylesheet" href="css/colors/cyan.css" />-->
<!--<link rel="stylesheet" href="css/colors/mossgreen.css" />-->
<style type="text/css">
@media only screen and (max-width:999px) and (min-width:480px){
	.table-style-2 td:nth-of-type(1):before { content: ""; }
	.table-style-2 td:nth-of-type(2):before { content: "(107學年度收入:元) "; }
	.table-style-2 td:nth-of-type(3):before { content: "(107學年度比率%) "; }
	.table-style-2 td:nth-of-type(4):before { content: "(108學年度收入:元) "; }
	.table-style-2 td:nth-of-type(5):before { content: "(108學年度比率%) "; }
	.table-style-2 td:nth-of-type(6):before { content: "(109學年度收入:元) "; }
	.table-style-2 td:nth-of-type(7):before { content: "(109學年度比率%) "; }
}
@media only screen and (max-width: 479px){
	.table-style-2 td:nth-of-type(1):before { content: ""; }
	.table-style-2 td:nth-of-type(2):before { content: "(107學年度收入:元) "; }
	.table-style-2 td:nth-of-type(3):before { content: "(107學年度比率%) "; }
	.table-style-2 td:nth-of-type(4):before { content: "(108學年度收入:元) "; }
	.table-style-2 td:nth-of-type(5):before { content: "(108學年度比率%) "; }
	.table-style-2 td:nth-of-type(6):before { content: "(109學年度收入:元) "; }
	.table-style-2 td:nth-of-type(7):before { content: "(109學年度比率%) "; }

}

.table-style-2 tr.subtotl1 {
    background: #f1f1f1;
}
.table-style-2 tr.subtotl2 {
    background: #fff /*e9f4ea*/;
}

.sec-tpadding{ padding-top:20px; }
.mybtn{ font-size:1.05em; background-color:#ffccd8;}
</style>

</head>

<body>
<div class="site_wrapper">
    <div class="topbar orange2 topbar-padding">

  </div>
  <div class="clearfix"></div>

  <div id="header">
    <div class="container">
      <div class="navbar navbar-default yamm dark2">
        <div class="navbar-header">
          <button type="button" data-toggle="collapse" data-target="#navbar-collapse-grid" class="navbar-toggle two three"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>

        </div>
        <div id="navbar-collapse-grid" class="navbar-collapse collapse pull-right">
          <ul class="nav navbar-nav">


            <li class="dropdown"> <a href="option1.aspx" class="dropdown-toggle">校務資訊說明</a>
              <ul class="dropdown-menu" role="menu">
                	<li><a href="intro.aspx">學校沿革</a> </li>
                    <li><a href="https://about.tku.edu.tw/organize.html" target='_blank'> 組織架構</a> </li>

                    <li class="dropdown-submenu mul"> <a tabindex="-1" href="#">基本數據及趨勢 + </a>
                      <ul class="dropdown-menu">
                        <li><a href="basicdata1.aspx">學生人數與變動趨勢圖</a></li>
                        <li><a href="basicdata2.aspx">教職員人數與變動趨勢圖</a></li>
                        <li><a href="basicdata3.aspx">生師比與變動趨勢圖</a></li>
                        <li><a href="basicdata4.aspx">每生校地及校舍面積</a></li>
                        <li><a href="basicdata5.aspx">學校圖書資源</a></li>
                        <li><a href="basicdata6.aspx">學校設備與資源</a></li>
                      </ul>
                    </li>

                    <li><a href="prospect.aspx"> 學校特色與發展願景</a> </li>
                    <li class="dropdown-submenu mul"><a tabindex="-1" href="#"> 學校績效表現 + </a>
                      <ul class="dropdown-menu">
                        <li><a href="effects1.aspx">各類評鑑結果</a></li>
                        <li><a href="effects2.aspx">各項績效表現</a></li>
                        <li><a href="effects3.aspx">畢業生流向與校友表現</a></li>
                       </ul>
                    </li>
                    <li><a href="https://about.tku.edu.tw/trustees/index.asp" target="_blank" title="連結董事會專區(另開視窗)">私立學校董事會相關資訊</a> </li>

              </ul>
            </li>

            <li class="dropdown"> <a href="option2.aspx" class="dropdown-toggle">財務資訊分析</a>
              <ul class="dropdown-menu" role="menu">
                	<li><a href="in_out_analy.aspx">學校收入分析</a> </li>
                    <li><a href="in_out_analy2.aspx">學校支出分析</a> </li>
              </ul>
            </li>

            <li class="dropdown"> <a href="option3.aspx" class="dropdown-toggle">學雜費與就學補助資訊</a>
              <ul class="dropdown-menu" role="menu">
                	<li><a href="allowance.aspx">學雜費收費標準</a> </li>
                    <li><a href="allowance2.aspx">平均教學成本</a> </li>
                    <li><a href="allowance3.aspx">學雜費佔教學成本比率</a> </li>
                    <li><a href="allowance4.aspx">在學期間教育支出估算</a> </li>
                    <li><a href="allowance5.aspx">各項助學措施資訊</a> </li>
                    <li><a href="allowance6.aspx">就學貸款/獎助學金/學雜費減免</a> </li>
                    <li><a href="use_layout.aspx">學雜費調整之用途規劃說明</a> </li>
                    <li><a href="discussion.aspx">學雜費調整校內審議程序說明</a> </li>
              </ul>
            </li>

            <li class="dropdown"> <a href="option4.aspx" class="dropdown-toggle">學校其他重要資訊</a>
              <ul class="dropdown-menu three" role="menu">
                <li> <a href="budget.aspx">預算編審程序</a> </li>
                <li> <a href="report.aspx">會計師查核報告</a> </li>
                <li> <a href="purchase.aspx">學校採購情形</a> </li>
                <li> <a href="handle.aspx">處分土地及重大資產</a> </li>
                <li> <a href="course.aspx">課程與師資</a> </li>
                <li> <a href="others.aspx">其他</a> </li>
              </ul>
            </li>
            <li class="dropdown"> <a href="option5.aspx" class="dropdown-toggle">內控內稽執行情形</a>
              <ul class="dropdown-menu two" role="menu">
                <li> <a href="doc/control.pdf" target="_blank">內部控制制度手冊 </a></li>
                <li> <a href="audit.aspx">內部控制制度作業程序</a> </li>
                <li> <a href="audit_point.aspx">內部控制重點</a> </li>
                <li> <a href="audit_rule.aspx">內部稽核作業規範</a> </li>
                <li> <a href="audit_report.aspx">稽核計畫及稽核報告</a> </li>
              </ul>
            </li>
            <li class="dropdown"> <a href="https://about.tku.edu.tw/trustees/index.asp" target="_blank" title="連結董事會專區(另開新視窗)">董事會相關資訊</a></li>

          </ul>
        </div>
      </div>
    </div>
  </div>
  <!--end menu-->


  <section>
    <div class="header-inner two">
      <div class="inner text-center">
        <h4 class="title text-white uppercase">財務資訊分析</h4>
<!--        <h5 class="text-white uppercase">Get Many More Features</h5>-->
      </div>
      <div class="overlay bg-opacity-5"></div>
<!--      <img src="images/header-img1.jpg" alt="" class="img-responsive"/> -->
      </div>
  </section>
  <!-- end header inner -->
  <div class="clearfix"></div>

  <section>
    <div class="pagenation-holder">
      <div class="container">

        <div class="row">
          <div class="col-md-6">
            <h3>學校支出分析</h3>
          </div>
          <div class="col-md-6 text-right">
            <div class="pagenation_links"><a href="index.aspx" title="回首頁"><i class="fa fa-home"></i></a><i> / </i> <a href="option2.aspx" title="回財務資訊分析選單">財務資訊分析</a> <i> / </i> 學校支出分析</div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--end section-->
  <div class="clearfix"></div>

 <section class="sec-tpadding sec-bpadding">
    <div class="container">
      <div class="row margin-top1">
 		<div class="col-md-2 col-md-offset-4 col-xs-4 col-xs-offset-2"><a href="#sec1" class="btn btn-border red-5 mybtn"><strong>成本與費用</strong></a></div>
        <div class="col-md-2 col-xs-4"><a href="#sec2" class="btn btn-border red-5 mybtn">資本支出</a> </div>
        <div class="clearfix margin-top3"></div>
        <div class="table-holder">
          <h3 class="section-title" id="sec1"><span class="text-orange-5">近3年成本與費用</span></h3>
		  <p class="contxt">　　本校成本與費用主要為教學研究及訓輔支出，近3學年度分別為23.13億元、21.96億元及21.69億元，占總支出近2/3。次要支出為行政管理支出，近3學年度分別為4.88億元、5.04億元及4.57億元，占總支出約14%。近3學年度撥付獎助學金分別為2.24億元、2.04億元及2.05億元，占總成本與費用從6.44%、5.79%及6.13%。</p>

        </div>
      </div>
    </div>
  </section>
  <!--end section-->
  <div class="clearfix"></div>

 <section class="sec-moreless-padding">
    <div class="container">
      <div class="row">

        <div class="table-holder">
          <h3 class="section-title"><span class="text-orange-5">107-109學年度<strong>成本與費用</strong>結構分析</span></h3>
          <table class="table-style-2 table-bordered">
            <thead>
              <tr>
                <th rowspan="2">成本與費用項目/學年度</th>
                <th colspan="2">107</th>
                <th colspan="2">108</th>
                <th colspan="2">109</th>

              </tr>
              <tr>
                <th>元</th>
                <th>%</th>
                <th>元</th>
                <th>%</th>
                <th>元</th>
                <th>%</th>
              </tr>
            </thead>
            <tbody>
              <tr class="subtotl1">
                <td>董事會支出 </td>
                <td><div class="text-right">4,712,199</div></td>
                <td><div class="text-right">0.14</div></td>
                <td><div class="text-right">5,034,515</div></td>
                <td><div class="text-right">0.14</div></td>
                <td><div class="text-right">4,806,637</div></td>
                <td><div class="text-right">0.14</div></td>
              </tr>
              <tr class="subtotl2">
                <td><div class="padding-left-1"> 人事費</div></td>
                <td><div class="text-right">3,425,297</div></td>
                <td><div class="text-right">0.10</div></td>
                <td><div class="text-right">3,761,400</div></td>
                <td><div class="text-right">0.11</div></td>
                <td><div class="text-right">3,761,400</div></td>
                <td><div class="text-right">0.11</div></td>
              </tr>
              <tr class="subtotl2">
                <td><div class="padding-left-1"> 業務費</div></td>
                <td><div class="text-right">294,834</div></td>
                <td><div class="text-right">0.01</div></td>
                <td><div class="text-right">331,545</div></td>
                <td><div class="text-right">0.01</div></td>
                <td><div class="text-right">221,943</div></td>
                <td><div class="text-right">0.01</div></td>
              </tr>
              <tr class="subtotl2">
                <td><div class="padding-left-1"> 維護費</div></td>
                <td><div class="text-right">16,380</div></td>
                <td><div class="text-right">0.00</div></td>
                <td><div class="text-right">0</div></td>
                <td><div class="text-right">0.00</div></td>
                <td><div class="text-right">0</div></td>
                <td><div class="text-right">0.00</div></td>
              </tr>
              <tr class="subtotl2">
                <td><div class="padding-left-1"> 出席及交通費</div></td>
                <td><div class="text-right">145,000</div></td>
                <td><div class="text-right">0.00</div></td>
                <td><div class="text-right">105,000</div></td>
                <td><div class="text-right">0.00</div></td>
                <td><div class="text-right">115,000</div></td>
                <td><div class="text-right">0.00</div></td>
              </tr>
              <tr class="subtotl2">
                <td><div class="padding-left-1"> 折舊及攤銷</div></td>
                <td><div class="text-right">830,688 </div></td>
                <td><div class="text-right">0.02</div></td>
                <td><div class="text-right">836,570 </div></td>
                <td><div class="text-right">0.02</div></td>
                <td><div class="text-right">708,294 </div></td>
                <td><div class="text-right">0.02</div></td>
              </tr>
              <tr class="subtotl1">
                <td>行政管理支出 </td>
                <td><div class="text-right">488,447,613</div></td>
                <td><div class="text-right">14.07</div></td>
                <td><div class="text-right">504,067,874</div></td>
                <td><div class="text-right">14.35</div></td>
                <td><div class="text-right">456,937,923</div></td>
                <td><div class="text-right">13.7</div></td>
              </tr>
              <tr class="subtotl2">
                <td><div class="padding-left-1"> 人事費</div></td>
                <td><div class="text-right">204,075,154</div></td>
                <td><div class="text-right">5.88</div></td>
                <td><div class="text-right">202,868,369</div></td>
                <td><div class="text-right">5.77</div></td>
                <td><div class="text-right">198,804,495 </div></td>
                <td><div class="text-right">5.96</div></td>
              </tr>
              <tr class="subtotl2">
                <td><div class="padding-left-1"> 業務費</div></td>
                <td><div class="text-right">127,588,638</div></td>
                <td><div class="text-right">3.67</div></td>
                <td><div class="text-right">120,314,818</div></td>
                <td><div class="text-right">3.42</div></td>
                <td><div class="text-right">120,503,981</div></td>
                <td><div class="text-right">3.61</div></td>
              </tr>
              <tr class="subtotl2">
                <td><div class="padding-left-1"> 維護費</div></td>
                <td><div class="text-right">84,750,314</div></td>
                <td><div class="text-right">2.44</div></td>
                <td><div class="text-right">96,504,987</div></td>
                <td><div class="text-right">2.75</div></td>
                <td><div class="text-right">62,266,230</div></td>
                <td><div class="text-right">1.87</div></td>
              </tr>
              <tr class="subtotl2">
                <td><div class="padding-left-1"> 退休撫卹費</div></td>
                <td><div class="text-right">12,142,008</div></td>
                <td><div class="text-right">0.35</div></td>
                <td><div class="text-right">11,079,756</div></td>
                <td><div class="text-right">0.32</div></td>
                <td><div class="text-right">9,296,620</div></td>
                <td><div class="text-right">0.28</div></td>
              </tr>
              <tr class="subtotl2">
                <td><div class="padding-left-1"> 折舊及攤銷</div></td>
                <td><div class="text-right">59,891,499</div></td>
                <td><div class="text-right">1.72</div></td>
                <td><div class="text-right">73,299,944</div></td>
                <td><div class="text-right">2.09</div></td>
                <td><div class="text-right">66,066,597</div></td>
                <td><div class="text-right">1.98</div></td>
              </tr>
              <tr class="subtotl1">
                <td>教學研究及訓輔支出</td>
                <td><div class="text-right">2,313,419,711</div></td>
                <td><div class="text-right">66.63</div></td>
                <td><div class="text-right">2,196,600,215</div></td>
                <td><div class="text-right">62.52</div></td>
                <td><div class="text-right">2,169,719,608 </div></td>
                <td><div class="text-right">65.04</div></td>
              </tr>
              <tr class="subtotl2">
                <td><div class="padding-left-1"> 人事費</div></td>
                <td><div class="text-right">1,580,098,453</div></td>
                <td><div class="text-right">45.51</div></td>
                <td><div class="text-right">1,546,308,145</div></td>
                <td><div class="text-right">44.01</div></td>
                <td><div class="text-right">1,562,653,376 </div></td>
                <td><div class="text-right">46.84</div></td>
              </tr>
              <tr class="subtotl2">
                <td><div class="padding-left-1"> 業務費</div></td>
                <td><div class="text-right">407,467,633</div></td>
                <td><div class="text-right">11.74</div></td>
                <td><div class="text-right">345,990,767</div></td>
                <td><div class="text-right">9.85</div></td>
                <td><div class="text-right">329,401,798</div></td>
                <td><div class="text-right">9.87</div></td>
              </tr>
              <tr class="subtotl2">
                <td><div class="padding-left-1"> 維護費</div></td>
                <td><div class="text-right">22,909,258</div></td>
                <td><div class="text-right">0.66</div></td>
                <td><div class="text-right">18,558,123</div></td>
                <td><div class="text-right">0.53</div></td>
                <td><div class="text-right">11,308,646</div></td>
                <td><div class="text-right">0.34</div></td>
              </tr>
              <tr class="subtotl2">
                <td><div class="padding-left-1"> 退休撫卹費</div></td>
                <td><div class="text-right">66,433,179</div></td>
                <td><div class="text-right">1.91</div></td>
                <td><div class="text-right">74,749,632</div></td>
                <td><div class="text-right">2.13</div></td>
                <td><div class="text-right">62,732,749</div></td>
                <td><div class="text-right">1.88</div></td>
              </tr>
              <tr class="subtotl2">
                <td><div class="padding-left-1"> 折舊及攤銷</div></td>
                <td><div class="text-right">236,511,188</div></td>
                <td><div class="text-right">6.81</div></td>
                <td><div class="text-right">210,993,548</div></td>
                <td><div class="text-right">6.01</div></td>
                <td><div class="text-right">203,623,039</div></td>
                <td><div class="text-right">6.1</div></td>
              </tr>
